version: "3"

tasks:
  migration:
    aliases:
      - mig
    desc: "Add db sqlite from migration files"
    cmds:
      - go run ./cmd/migrator --storage-path=./storage/sso.db --migrations-path=./migrations
  migration_test:
    aliases:
      - migtest
    desc: "Add test data for db"
    cmds:
      - go run ./cmd/migrator --storage-path=./storage/sso.db --migrations-path=./tests/migrations --migrations-table=migrations_test